[2022-05-12 07:40:29,420] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: live_stream_Dag.producer_twitter_data manual__2022-05-12T07:40:23.442797+00:00 [queued]>
[2022-05-12 07:40:29,426] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: live_stream_Dag.producer_twitter_data manual__2022-05-12T07:40:23.442797+00:00 [queued]>
[2022-05-12 07:40:29,427] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-05-12 07:40:29,428] {taskinstance.py:1357} INFO - Starting attempt 2 of 2
[2022-05-12 07:40:29,428] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-05-12 07:40:29,436] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): producer_twitter_data> on 2022-05-12 07:40:23.442797+00:00
[2022-05-12 07:40:29,441] {standard_task_runner.py:52} INFO - Started process 815 to run task
[2022-05-12 07:40:29,443] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'live_stream_Dag', 'producer_twitter_data', 'manual__2022-05-12T07:40:23.442797+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/live_stream_dag.py', '--cfg-path', '/tmp/tmppujs6eji', '--error-file', '/tmp/tmpmf9vut5v']
[2022-05-12 07:40:29,445] {standard_task_runner.py:80} INFO - Job 9: Subtask producer_twitter_data
[2022-05-12 07:40:29,486] {task_command.py:369} INFO - Running <TaskInstance: live_stream_Dag.producer_twitter_data manual__2022-05-12T07:40:23.442797+00:00 [running]> on host c5e465c36164
[2022-05-12 07:40:29,542] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Airflow
AIRFLOW_CTX_DAG_ID=live_stream_Dag
AIRFLOW_CTX_TASK_ID=producer_twitter_data
AIRFLOW_CTX_EXECUTION_DATE=2022-05-12T07:40:23.442797+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-05-12T07:40:23.442797+00:00
[2022-05-12 07:40:29,545] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-05-12 07:40:29,546] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python3 /opt/***/dags/producer_tweets.py']
[2022-05-12 07:40:29,555] {subprocess.py:85} INFO - Output:
[2022-05-12 07:40:29,588] {subprocess.py:92} INFO - Traceback (most recent call last):
[2022-05-12 07:40:29,590] {subprocess.py:92} INFO -   File "/opt/***/dags/producer_tweets.py", line 1, in <module>
[2022-05-12 07:40:29,590] {subprocess.py:92} INFO -     from tweepy import OAuthHandler
[2022-05-12 07:40:29,591] {subprocess.py:92} INFO - ModuleNotFoundError: No module named 'tweepy'
[2022-05-12 07:40:29,592] {subprocess.py:96} INFO - Command exited with return code 1
[2022-05-12 07:40:29,658] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-05-12 07:40:29,661] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=live_stream_Dag, task_id=producer_twitter_data, execution_date=20220512T074023, start_date=20220512T074029, end_date=20220512T074029
[2022-05-12 07:40:29,758] {standard_task_runner.py:97} ERROR - Failed to execute job 9 for task producer_twitter_data (Bash command failed. The command returned a non-zero exit code 1.; 815)
[2022-05-12 07:40:29,779] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-05-12 07:40:29,797] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
