[2022-05-12 15:03:07,999] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: live_stream_Dag.producer_twitter_data manual__2022-05-12T15:03:07.550913+00:00 [queued]>
[2022-05-12 15:03:08,007] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: live_stream_Dag.producer_twitter_data manual__2022-05-12T15:03:07.550913+00:00 [queued]>
[2022-05-12 15:03:08,008] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-05-12 15:03:08,009] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-05-12 15:03:08,010] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-05-12 15:03:08,021] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): producer_twitter_data> on 2022-05-12 15:03:07.550913+00:00
[2022-05-12 15:03:08,026] {standard_task_runner.py:52} INFO - Started process 2098 to run task
[2022-05-12 15:03:08,032] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'live_stream_Dag', 'producer_twitter_data', 'manual__2022-05-12T15:03:07.550913+00:00', '--job-id', '80', '--raw', '--subdir', 'DAGS_FOLDER/live_stream_dag.py', '--cfg-path', '/tmp/tmpff26in4m', '--error-file', '/tmp/tmpujg4i1fy']
[2022-05-12 15:03:08,035] {standard_task_runner.py:80} INFO - Job 80: Subtask producer_twitter_data
[2022-05-12 15:03:08,113] {task_command.py:369} INFO - Running <TaskInstance: live_stream_Dag.producer_twitter_data manual__2022-05-12T15:03:07.550913+00:00 [running]> on host 78a2fc18e687
[2022-05-12 15:03:08,297] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Airflow
AIRFLOW_CTX_DAG_ID=live_stream_Dag
AIRFLOW_CTX_TASK_ID=producer_twitter_data
AIRFLOW_CTX_EXECUTION_DATE=2022-05-12T15:03:07.550913+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-05-12T15:03:07.550913+00:00
[2022-05-12 15:03:08,298] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-05-12 15:03:08,300] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python3 /opt/***/dags/producer_tweets.py']
[2022-05-12 15:03:08,307] {subprocess.py:85} INFO - Output:
[2022-05-12 15:03:08,710] {subprocess.py:92} INFO - Traceback (most recent call last):
[2022-05-12 15:03:08,712] {subprocess.py:92} INFO -   File "/opt/***/dags/producer_tweets.py", line 21, in <module>
[2022-05-12 15:03:08,712] {subprocess.py:92} INFO -     producer = KafkaProducer(bootstrap_servers='localhost:9092')
[2022-05-12 15:03:08,715] {subprocess.py:92} INFO -   File "/home/***/.local/lib/python3.7/site-packages/kafka/producer/kafka.py", line 383, in __init__
[2022-05-12 15:03:08,717] {subprocess.py:92} INFO -     **self.config)
[2022-05-12 15:03:08,719] {subprocess.py:92} INFO -   File "/home/***/.local/lib/python3.7/site-packages/kafka/client_async.py", line 244, in __init__
[2022-05-12 15:03:08,720] {subprocess.py:92} INFO -     self.config['api_version'] = self.check_version(timeout=check_timeout)
[2022-05-12 15:03:08,721] {subprocess.py:92} INFO -   File "/home/***/.local/lib/python3.7/site-packages/kafka/client_async.py", line 900, in check_version
[2022-05-12 15:03:08,724] {subprocess.py:92} INFO -     raise Errors.NoBrokersAvailable()
[2022-05-12 15:03:08,725] {subprocess.py:92} INFO - kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2022-05-12 15:03:08,735] {subprocess.py:96} INFO - Command exited with return code 1
[2022-05-12 15:03:08,759] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-05-12 15:03:08,765] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=live_stream_Dag, task_id=producer_twitter_data, execution_date=20220512T150307, start_date=20220512T150308, end_date=20220512T150308
[2022-05-12 15:03:08,780] {standard_task_runner.py:97} ERROR - Failed to execute job 80 for task producer_twitter_data (Bash command failed. The command returned a non-zero exit code 1.; 2098)
[2022-05-12 15:03:08,814] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-05-12 15:03:08,852] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
