[2022-05-12 14:52:59,851] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: live_stream_Dag.producer_twitter_data manual__2022-05-12T14:52:52.314100+00:00 [queued]>
[2022-05-12 14:52:59,856] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: live_stream_Dag.producer_twitter_data manual__2022-05-12T14:52:52.314100+00:00 [queued]>
[2022-05-12 14:52:59,857] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-05-12 14:52:59,858] {taskinstance.py:1357} INFO - Starting attempt 2 of 2
[2022-05-12 14:52:59,859] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-05-12 14:52:59,867] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): producer_twitter_data> on 2022-05-12 14:52:52.314100+00:00
[2022-05-12 14:52:59,871] {standard_task_runner.py:52} INFO - Started process 636 to run task
[2022-05-12 14:52:59,873] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'live_stream_Dag', 'producer_twitter_data', 'manual__2022-05-12T14:52:52.314100+00:00', '--job-id', '75', '--raw', '--subdir', 'DAGS_FOLDER/live_stream_dag.py', '--cfg-path', '/tmp/tmptnyv1tpy', '--error-file', '/tmp/tmp_7zdc_db']
[2022-05-12 14:52:59,875] {standard_task_runner.py:80} INFO - Job 75: Subtask producer_twitter_data
[2022-05-12 14:52:59,920] {task_command.py:369} INFO - Running <TaskInstance: live_stream_Dag.producer_twitter_data manual__2022-05-12T14:52:52.314100+00:00 [running]> on host 03e32d4c4ad1
[2022-05-12 14:53:00,062] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Airflow
AIRFLOW_CTX_DAG_ID=live_stream_Dag
AIRFLOW_CTX_TASK_ID=producer_twitter_data
AIRFLOW_CTX_EXECUTION_DATE=2022-05-12T14:52:52.314100+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-05-12T14:52:52.314100+00:00
[2022-05-12 14:53:00,065] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-05-12 14:53:00,066] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python3 /opt/***/dags/producer_tweets.py']
[2022-05-12 14:53:00,073] {subprocess.py:85} INFO - Output:
[2022-05-12 14:53:00,440] {subprocess.py:92} INFO - Traceback (most recent call last):
[2022-05-12 14:53:00,441] {subprocess.py:92} INFO -   File "/opt/***/dags/producer_tweets.py", line 21, in <module>
[2022-05-12 14:53:00,442] {subprocess.py:92} INFO -     producer = KafkaProducer(bootstrap_servers='localhost:9092')
[2022-05-12 14:53:00,443] {subprocess.py:92} INFO -   File "/home/***/.local/lib/python3.7/site-packages/kafka/producer/kafka.py", line 383, in __init__
[2022-05-12 14:53:00,444] {subprocess.py:92} INFO -     **self.config)
[2022-05-12 14:53:00,444] {subprocess.py:92} INFO -   File "/home/***/.local/lib/python3.7/site-packages/kafka/client_async.py", line 244, in __init__
[2022-05-12 14:53:00,445] {subprocess.py:92} INFO -     self.config['api_version'] = self.check_version(timeout=check_timeout)
[2022-05-12 14:53:00,446] {subprocess.py:92} INFO -   File "/home/***/.local/lib/python3.7/site-packages/kafka/client_async.py", line 900, in check_version
[2022-05-12 14:53:00,447] {subprocess.py:92} INFO -     raise Errors.NoBrokersAvailable()
[2022-05-12 14:53:00,448] {subprocess.py:92} INFO - kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2022-05-12 14:53:00,457] {subprocess.py:96} INFO - Command exited with return code 1
[2022-05-12 14:53:00,468] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-05-12 14:53:00,471] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=live_stream_Dag, task_id=producer_twitter_data, execution_date=20220512T145252, start_date=20220512T145259, end_date=20220512T145300
[2022-05-12 14:53:00,477] {standard_task_runner.py:97} ERROR - Failed to execute job 75 for task producer_twitter_data (Bash command failed. The command returned a non-zero exit code 1.; 636)
[2022-05-12 14:53:00,498] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-05-12 14:53:00,517] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
