[2022-05-12 15:11:34,532] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: live_stream_Dag.consumer_twitter_data manual__2022-05-12T15:11:34.156532+00:00 [queued]>
[2022-05-12 15:11:34,539] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: live_stream_Dag.consumer_twitter_data manual__2022-05-12T15:11:34.156532+00:00 [queued]>
[2022-05-12 15:11:34,540] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-05-12 15:11:34,541] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-05-12 15:11:34,542] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-05-12 15:11:34,551] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): consumer_twitter_data> on 2022-05-12 15:11:34.156532+00:00
[2022-05-12 15:11:34,557] {standard_task_runner.py:52} INFO - Started process 1498 to run task
[2022-05-12 15:11:34,559] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'live_stream_Dag', 'consumer_twitter_data', 'manual__2022-05-12T15:11:34.156532+00:00', '--job-id', '93', '--raw', '--subdir', 'DAGS_FOLDER/live_stream_dag.py', '--cfg-path', '/tmp/tmppk3bvfy6', '--error-file', '/tmp/tmps63y3wth']
[2022-05-12 15:11:34,561] {standard_task_runner.py:80} INFO - Job 93: Subtask consumer_twitter_data
[2022-05-12 15:11:34,608] {task_command.py:369} INFO - Running <TaskInstance: live_stream_Dag.consumer_twitter_data manual__2022-05-12T15:11:34.156532+00:00 [running]> on host 29272fb26059
[2022-05-12 15:11:34,810] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Airflow
AIRFLOW_CTX_DAG_ID=live_stream_Dag
AIRFLOW_CTX_TASK_ID=consumer_twitter_data
AIRFLOW_CTX_EXECUTION_DATE=2022-05-12T15:11:34.156532+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-05-12T15:11:34.156532+00:00
[2022-05-12 15:11:34,812] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-05-12 15:11:34,814] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python3 /opt/***/dags/consumer_tweets.py']
[2022-05-12 15:11:34,822] {subprocess.py:85} INFO - Output:
[2022-05-12 15:11:35,774] {subprocess.py:92} INFO - WARNING: An illegal reflective access operation has occurred
[2022-05-12 15:11:35,776] {subprocess.py:92} INFO - WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/home/***/.local/lib/python3.7/site-packages/pyspark/jars/spark-unsafe_2.12-3.2.1.jar) to constructor java.nio.DirectByteBuffer(long,int)
[2022-05-12 15:11:35,777] {subprocess.py:92} INFO - WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
[2022-05-12 15:11:35,778] {subprocess.py:92} INFO - WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
[2022-05-12 15:11:35,779] {subprocess.py:92} INFO - WARNING: All illegal access operations will be denied in a future release
[2022-05-12 15:11:35,849] {subprocess.py:92} INFO - :: loading settings :: url = jar:file:/home/***/.local/lib/python3.7/site-packages/pyspark/jars/ivy-2.5.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2022-05-12 15:11:35,902] {subprocess.py:92} INFO - Ivy Default Cache set to: /home/***/.ivy2/cache
[2022-05-12 15:11:35,904] {subprocess.py:92} INFO - The jars for the packages stored in: /home/***/.ivy2/jars
[2022-05-12 15:11:35,905] {subprocess.py:92} INFO - org.apache.spark#spark-streaming-kafka-0-10_2.12 added as a dependency
[2022-05-12 15:11:35,906] {subprocess.py:92} INFO - org.apache.spark#spark-sql-kafka-0-10_2.12 added as a dependency
[2022-05-12 15:11:35,907] {subprocess.py:92} INFO - org.mongodb.spark#mongo-spark-connector_2.12 added as a dependency
[2022-05-12 15:11:35,908] {subprocess.py:92} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-5df372ee-2a55-4d59-b45b-8b7b9182afb2;1.0
[2022-05-12 15:11:35,909] {subprocess.py:92} INFO - 	confs: [default]
[2022-05-12 15:11:35,989] {subprocess.py:92} INFO - 	found org.apache.spark#spark-streaming-kafka-0-10_2.12;3.1.0 in central
[2022-05-12 15:11:36,023] {subprocess.py:92} INFO - 	found org.apache.spark#spark-token-provider-kafka-0-10_2.12;3.1.0 in central
[2022-05-12 15:11:36,037] {subprocess.py:92} INFO - 	found org.apache.kafka#kafka-clients;2.6.0 in central
[2022-05-12 15:11:36,050] {subprocess.py:92} INFO - 	found com.github.luben#zstd-jni;1.4.8-1 in central
[2022-05-12 15:11:36,060] {subprocess.py:92} INFO - 	found org.lz4#lz4-java;1.7.1 in central
[2022-05-12 15:11:36,079] {subprocess.py:92} INFO - 	found org.xerial.snappy#snappy-java;1.1.8.2 in central
[2022-05-12 15:11:41,658] {subprocess.py:92} INFO - 	found org.slf4j#slf4j-api;1.7.30 in central
[2022-05-12 15:11:45,496] {subprocess.py:92} INFO - 	found org.spark-project.spark#unused;1.0.0 in central
[2022-05-12 15:11:47,292] {subprocess.py:92} INFO - 	found org.apache.spark#spark-sql-kafka-0-10_2.12;3.1.0 in central
[2022-05-12 15:11:49,727] {local_task_job.py:221} WARNING - State of this instance has been externally set to success. Terminating instance.
[2022-05-12 15:11:49,732] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 1498. PIDs of all processes in the group: [1501, 1507, 1498]
[2022-05-12 15:11:49,733] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 1498
[2022-05-12 15:11:49,734] {taskinstance.py:1541} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-05-12 15:11:49,736] {subprocess.py:103} INFO - Sending SIGTERM signal to process group
[2022-05-12 15:11:49,827] {process_utils.py:75} INFO - Process psutil.Process(pid=1501, status='terminated', started='15:11:34') (1501) terminated with exit code None
[2022-05-12 15:11:49,829] {process_utils.py:75} INFO - Process psutil.Process(pid=1498, status='terminated', exitcode=0, started='15:11:34') (1498) terminated with exit code 0
[2022-05-12 15:11:50,051] {process_utils.py:75} INFO - Process psutil.Process(pid=1507, status='terminated', started='15:11:34') (1507) terminated with exit code None
