[2022-05-12 07:55:37,546] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: live_stream_Dag.producer_twitter_data manual__2022-05-12T07:55:36.930066+00:00 [queued]>
[2022-05-12 07:55:37,552] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: live_stream_Dag.producer_twitter_data manual__2022-05-12T07:55:36.930066+00:00 [queued]>
[2022-05-12 07:55:37,558] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-05-12 07:55:37,559] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-05-12 07:55:37,560] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-05-12 07:55:37,569] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): producer_twitter_data> on 2022-05-12 07:55:36.930066+00:00
[2022-05-12 07:55:37,574] {standard_task_runner.py:52} INFO - Started process 376 to run task
[2022-05-12 07:55:37,579] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'live_stream_Dag', 'producer_twitter_data', 'manual__2022-05-12T07:55:36.930066+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/live_stream_dag.py', '--cfg-path', '/tmp/tmpuchnj91b', '--error-file', '/tmp/tmp43ye5uv4']
[2022-05-12 07:55:37,581] {standard_task_runner.py:80} INFO - Job 19: Subtask producer_twitter_data
[2022-05-12 07:55:37,635] {task_command.py:369} INFO - Running <TaskInstance: live_stream_Dag.producer_twitter_data manual__2022-05-12T07:55:36.930066+00:00 [running]> on host f74a48c86df7
[2022-05-12 07:55:37,833] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Airflow
AIRFLOW_CTX_DAG_ID=live_stream_Dag
AIRFLOW_CTX_TASK_ID=producer_twitter_data
AIRFLOW_CTX_EXECUTION_DATE=2022-05-12T07:55:36.930066+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-05-12T07:55:36.930066+00:00
[2022-05-12 07:55:37,834] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-05-12 07:55:37,835] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python3 /opt/***/dags/producer_tweets.py']
[2022-05-12 07:55:37,844] {subprocess.py:85} INFO - Output:
[2022-05-12 07:55:38,143] {subprocess.py:92} INFO - Traceback (most recent call last):
[2022-05-12 07:55:38,143] {subprocess.py:92} INFO -   File "/opt/***/dags/producer_tweets.py", line 10, in <module>
[2022-05-12 07:55:38,144] {subprocess.py:92} INFO -     consumer_key = config['twitter']['api_key']
[2022-05-12 07:55:38,145] {subprocess.py:92} INFO -   File "/usr/local/lib/python3.7/configparser.py", line 958, in __getitem__
[2022-05-12 07:55:38,147] {subprocess.py:92} INFO -     raise KeyError(key)
[2022-05-12 07:55:38,149] {subprocess.py:92} INFO - KeyError: 'twitter'
[2022-05-12 07:55:38,158] {subprocess.py:96} INFO - Command exited with return code 1
[2022-05-12 07:55:38,169] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-05-12 07:55:38,172] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=live_stream_Dag, task_id=producer_twitter_data, execution_date=20220512T075536, start_date=20220512T075537, end_date=20220512T075538
[2022-05-12 07:55:38,179] {standard_task_runner.py:97} ERROR - Failed to execute job 19 for task producer_twitter_data (Bash command failed. The command returned a non-zero exit code 1.; 376)
[2022-05-12 07:55:38,196] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-05-12 07:55:38,218] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
