[2022-05-13 07:27:26,049] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: live_stream_Dag.producer_twitter_data manual__2022-05-13T07:27:24.604600+00:00 [queued]>
[2022-05-13 07:27:26,059] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: live_stream_Dag.producer_twitter_data manual__2022-05-13T07:27:24.604600+00:00 [queued]>
[2022-05-13 07:27:26,060] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-05-13 07:27:26,061] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-05-13 07:27:26,062] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-05-13 07:27:26,076] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): producer_twitter_data> on 2022-05-13 07:27:24.604600+00:00
[2022-05-13 07:27:26,083] {standard_task_runner.py:52} INFO - Started process 606 to run task
[2022-05-13 07:27:26,090] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'live_stream_Dag', 'producer_twitter_data', 'manual__2022-05-13T07:27:24.604600+00:00', '--job-id', '125', '--raw', '--subdir', 'DAGS_FOLDER/live_stream_dag.py', '--cfg-path', '/tmp/tmp1jjd0hb4', '--error-file', '/tmp/tmpp1da_ua8']
[2022-05-13 07:27:26,092] {standard_task_runner.py:80} INFO - Job 125: Subtask producer_twitter_data
[2022-05-13 07:27:26,152] {task_command.py:369} INFO - Running <TaskInstance: live_stream_Dag.producer_twitter_data manual__2022-05-13T07:27:24.604600+00:00 [running]> on host 034a9584f865
[2022-05-13 07:27:26,356] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Airflow
AIRFLOW_CTX_DAG_ID=live_stream_Dag
AIRFLOW_CTX_TASK_ID=producer_twitter_data
AIRFLOW_CTX_EXECUTION_DATE=2022-05-13T07:27:24.604600+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-05-13T07:27:24.604600+00:00
[2022-05-13 07:27:26,358] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-05-13 07:27:26,359] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python3 /opt/***/dags/producer_tweets.py']
[2022-05-13 07:27:26,379] {subprocess.py:85} INFO - Output:
[2022-05-13 07:28:27,893] {subprocess.py:92} INFO - Stream encountered an exception
[2022-05-13 07:28:27,911] {subprocess.py:92} INFO - Traceback (most recent call last):
[2022-05-13 07:28:27,912] {subprocess.py:92} INFO -   File "/home/***/.local/lib/python3.7/site-packages/tweepy/streaming.py", line 91, in _connect
[2022-05-13 07:28:27,913] {subprocess.py:92} INFO -     self.on_data(line)
[2022-05-13 07:28:27,915] {subprocess.py:92} INFO -   File "/opt/***/dags/producer_tweets.py", line 57, in on_data
[2022-05-13 07:28:27,916] {subprocess.py:92} INFO -     producer.send('covid_topic', value=json_str)
[2022-05-13 07:28:27,917] {subprocess.py:92} INFO -   File "/home/***/.local/lib/python3.7/site-packages/kafka/producer/kafka.py", line 576, in send
[2022-05-13 07:28:27,918] {subprocess.py:92} INFO -     self._wait_on_metadata(topic, self.config['max_block_ms'] / 1000.0)
[2022-05-13 07:28:27,919] {subprocess.py:92} INFO -   File "/home/***/.local/lib/python3.7/site-packages/kafka/producer/kafka.py", line 703, in _wait_on_metadata
[2022-05-13 07:28:27,921] {subprocess.py:92} INFO -     "Failed to update metadata after %.1f secs." % (max_wait,))
[2022-05-13 07:28:27,923] {subprocess.py:92} INFO - kafka.errors.KafkaTimeoutError: KafkaTimeoutError: Failed to update metadata after 60.0 secs.
[2022-05-13 07:28:41,953] {subprocess.py:96} INFO - Command exited with return code -9
[2022-05-13 07:28:42,004] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code -9.
[2022-05-13 07:28:42,019] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=live_stream_Dag, task_id=producer_twitter_data, execution_date=20220513T072724, start_date=20220513T072726, end_date=20220513T072842
[2022-05-13 07:28:42,047] {standard_task_runner.py:97} ERROR - Failed to execute job 125 for task producer_twitter_data (Bash command failed. The command returned a non-zero exit code -9.; 606)
[2022-05-13 07:28:42,125] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-05-13 07:28:42,155] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
