[2022-05-12 15:04:10,982] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: live_stream_Dag.consumer_twitter_data manual__2022-05-12T15:04:10.586406+00:00 [queued]>
[2022-05-12 15:04:10,988] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: live_stream_Dag.consumer_twitter_data manual__2022-05-12T15:04:10.586406+00:00 [queued]>
[2022-05-12 15:04:10,988] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-05-12 15:04:10,989] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-05-12 15:04:10,990] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-05-12 15:04:10,998] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): consumer_twitter_data> on 2022-05-12 15:04:10.586406+00:00
[2022-05-12 15:04:11,002] {standard_task_runner.py:52} INFO - Started process 2623 to run task
[2022-05-12 15:04:11,005] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'live_stream_Dag', 'consumer_twitter_data', 'manual__2022-05-12T15:04:10.586406+00:00', '--job-id', '83', '--raw', '--subdir', 'DAGS_FOLDER/live_stream_dag.py', '--cfg-path', '/tmp/tmpb1vu7zy7', '--error-file', '/tmp/tmpczx1r964']
[2022-05-12 15:04:11,007] {standard_task_runner.py:80} INFO - Job 83: Subtask consumer_twitter_data
[2022-05-12 15:04:11,050] {task_command.py:369} INFO - Running <TaskInstance: live_stream_Dag.consumer_twitter_data manual__2022-05-12T15:04:10.586406+00:00 [running]> on host 78a2fc18e687
[2022-05-12 15:04:11,198] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Airflow
AIRFLOW_CTX_DAG_ID=live_stream_Dag
AIRFLOW_CTX_TASK_ID=consumer_twitter_data
AIRFLOW_CTX_EXECUTION_DATE=2022-05-12T15:04:10.586406+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-05-12T15:04:10.586406+00:00
[2022-05-12 15:04:11,200] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-05-12 15:04:11,201] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python3 /opt/***/dags/consumer_tweets.py']
[2022-05-12 15:04:11,209] {subprocess.py:85} INFO - Output:
[2022-05-12 15:04:12,092] {subprocess.py:92} INFO - WARNING: An illegal reflective access operation has occurred
[2022-05-12 15:04:12,094] {subprocess.py:92} INFO - WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/home/***/.local/lib/python3.7/site-packages/pyspark/jars/spark-unsafe_2.12-3.2.1.jar) to constructor java.nio.DirectByteBuffer(long,int)
[2022-05-12 15:04:12,095] {subprocess.py:92} INFO - WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
[2022-05-12 15:04:12,096] {subprocess.py:92} INFO - WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
[2022-05-12 15:04:12,097] {subprocess.py:92} INFO - WARNING: All illegal access operations will be denied in a future release
[2022-05-12 15:04:12,171] {subprocess.py:92} INFO - :: loading settings :: url = jar:file:/home/***/.local/lib/python3.7/site-packages/pyspark/jars/ivy-2.5.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2022-05-12 15:04:12,218] {subprocess.py:92} INFO - Ivy Default Cache set to: /home/***/.ivy2/cache
[2022-05-12 15:04:12,219] {subprocess.py:92} INFO - The jars for the packages stored in: /home/***/.ivy2/jars
[2022-05-12 15:04:12,221] {subprocess.py:92} INFO - org.apache.spark#spark-streaming-kafka-0-10_2.12 added as a dependency
[2022-05-12 15:04:12,222] {subprocess.py:92} INFO - org.apache.spark#spark-sql-kafka-0-10_2.12 added as a dependency
[2022-05-12 15:04:12,223] {subprocess.py:92} INFO - org.mongodb.spark#mongo-spark-connector_2.12 added as a dependency
[2022-05-12 15:04:12,224] {subprocess.py:92} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-e855c688-4e15-4722-b81b-2561077216e4;1.0
[2022-05-12 15:04:12,225] {subprocess.py:92} INFO - 	confs: [default]
[2022-05-12 15:04:12,301] {subprocess.py:92} INFO - 	found org.apache.spark#spark-streaming-kafka-0-10_2.12;3.1.0 in central
[2022-05-12 15:04:12,329] {subprocess.py:92} INFO - 	found org.apache.spark#spark-token-provider-kafka-0-10_2.12;3.1.0 in central
[2022-05-12 15:04:12,342] {subprocess.py:92} INFO - 	found org.apache.kafka#kafka-clients;2.6.0 in central
[2022-05-12 15:04:12,359] {subprocess.py:92} INFO - 	found com.github.luben#zstd-jni;1.4.8-1 in central
[2022-05-12 15:04:12,369] {subprocess.py:92} INFO - 	found org.lz4#lz4-java;1.7.1 in central
[2022-05-12 15:04:12,378] {subprocess.py:92} INFO - 	found org.xerial.snappy#snappy-java;1.1.8.2 in central
[2022-05-12 15:04:12,386] {subprocess.py:92} INFO - 	found org.slf4j#slf4j-api;1.7.30 in central
[2022-05-12 15:04:12,395] {subprocess.py:92} INFO - 	found org.spark-project.spark#unused;1.0.0 in central
[2022-05-12 15:04:12,412] {subprocess.py:92} INFO - 	found org.apache.spark#spark-sql-kafka-0-10_2.12;3.1.0 in central
[2022-05-12 15:04:12,423] {subprocess.py:92} INFO - 	found org.apache.commons#commons-pool2;2.6.2 in central
[2022-05-12 15:04:12,435] {subprocess.py:92} INFO - 	found org.mongodb.spark#mongo-spark-connector_2.12;3.0.1 in central
[2022-05-12 15:04:12,441] {subprocess.py:92} INFO - 	found org.mongodb#mongodb-driver-sync;4.0.5 in central
[2022-05-12 15:04:12,446] {subprocess.py:92} INFO - 	found org.mongodb#bson;4.0.5 in central
[2022-05-12 15:04:12,452] {subprocess.py:92} INFO - 	found org.mongodb#mongodb-driver-core;4.0.5 in central
[2022-05-12 15:04:14,022] {subprocess.py:92} INFO - downloading https://repo1.maven.org/maven2/com/github/luben/zstd-jni/1.4.8-1/zstd-jni-1.4.8-1.jar ...
[2022-05-12 15:04:54,143] {subprocess.py:92} INFO - 	[SUCCESSFUL ] com.github.luben#zstd-jni;1.4.8-1!zstd-jni.jar (41676ms)
[2022-05-12 15:04:54,481] {subprocess.py:92} INFO - downloading https://repo1.maven.org/maven2/org/lz4/lz4-java/1.7.1/lz4-java-1.7.1.jar ...
[2022-05-12 15:05:01,746] {local_task_job.py:221} WARNING - State of this instance has been externally set to success. Terminating instance.
[2022-05-12 15:05:01,757] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 2623. PIDs of all processes in the group: [2626, 2632, 2638, 2623]
[2022-05-12 15:05:01,758] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 2623
[2022-05-12 15:05:01,761] {taskinstance.py:1541} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-05-12 15:05:01,763] {subprocess.py:103} INFO - Sending SIGTERM signal to process group
[2022-05-12 15:05:01,903] {process_utils.py:75} INFO - Process psutil.Process(pid=2638, status='terminated', started='15:04:10') (2638) terminated with exit code None
[2022-05-12 15:05:02,040] {process_utils.py:75} INFO - Process psutil.Process(pid=2632, status='terminated', started='15:04:10') (2632) terminated with exit code None
[2022-05-12 15:05:02,041] {process_utils.py:75} INFO - Process psutil.Process(pid=2623, status='terminated', exitcode=0, started='15:04:10') (2623) terminated with exit code 0
[2022-05-12 15:05:02,042] {process_utils.py:75} INFO - Process psutil.Process(pid=2626, status='terminated', started='15:04:10') (2626) terminated with exit code None
