[2022-05-13 06:14:30,141] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: live_stream_Dag.producer_twitter_data manual__2022-05-13T06:14:29.666832+00:00 [queued]>
[2022-05-13 06:14:30,148] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: live_stream_Dag.producer_twitter_data manual__2022-05-13T06:14:29.666832+00:00 [queued]>
[2022-05-13 06:14:30,149] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-05-13 06:14:30,150] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-05-13 06:14:30,152] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-05-13 06:14:30,162] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): producer_twitter_data> on 2022-05-13 06:14:29.666832+00:00
[2022-05-13 06:14:30,170] {standard_task_runner.py:52} INFO - Started process 373 to run task
[2022-05-13 06:14:30,174] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'live_stream_Dag', 'producer_twitter_data', 'manual__2022-05-13T06:14:29.666832+00:00', '--job-id', '122', '--raw', '--subdir', 'DAGS_FOLDER/live_stream_dag.py', '--cfg-path', '/tmp/tmptnnt5way', '--error-file', '/tmp/tmpkt0qhtad']
[2022-05-13 06:14:30,176] {standard_task_runner.py:80} INFO - Job 122: Subtask producer_twitter_data
[2022-05-13 06:14:30,234] {task_command.py:369} INFO - Running <TaskInstance: live_stream_Dag.producer_twitter_data manual__2022-05-13T06:14:29.666832+00:00 [running]> on host 72d815214583
[2022-05-13 06:14:30,431] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Airflow
AIRFLOW_CTX_DAG_ID=live_stream_Dag
AIRFLOW_CTX_TASK_ID=producer_twitter_data
AIRFLOW_CTX_EXECUTION_DATE=2022-05-13T06:14:29.666832+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-05-13T06:14:29.666832+00:00
[2022-05-13 06:14:30,433] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-05-13 06:14:30,434] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python3 /opt/***/dags/producer_tweets.py']
[2022-05-13 06:14:30,442] {subprocess.py:85} INFO - Output:
[2022-05-13 06:15:31,648] {subprocess.py:92} INFO - Stream encountered an exception
[2022-05-13 06:15:31,652] {subprocess.py:92} INFO - Traceback (most recent call last):
[2022-05-13 06:15:31,653] {subprocess.py:92} INFO -   File "/home/***/.local/lib/python3.7/site-packages/tweepy/streaming.py", line 91, in _connect
[2022-05-13 06:15:31,656] {subprocess.py:92} INFO -     self.on_data(line)
[2022-05-13 06:15:31,658] {subprocess.py:92} INFO -   File "/opt/***/dags/producer_tweets.py", line 57, in on_data
[2022-05-13 06:15:31,662] {subprocess.py:92} INFO -     producer.send('covid_topic', value=json_str)
[2022-05-13 06:15:31,665] {subprocess.py:92} INFO -   File "/home/***/.local/lib/python3.7/site-packages/kafka/producer/kafka.py", line 576, in send
[2022-05-13 06:15:31,667] {subprocess.py:92} INFO -     self._wait_on_metadata(topic, self.config['max_block_ms'] / 1000.0)
[2022-05-13 06:15:31,668] {subprocess.py:92} INFO -   File "/home/***/.local/lib/python3.7/site-packages/kafka/producer/kafka.py", line 703, in _wait_on_metadata
[2022-05-13 06:15:31,669] {subprocess.py:92} INFO -     "Failed to update metadata after %.1f secs." % (max_wait,))
[2022-05-13 06:15:31,671] {subprocess.py:92} INFO - kafka.errors.KafkaTimeoutError: KafkaTimeoutError: Failed to update metadata after 60.0 secs.
[2022-05-13 06:15:55,913] {local_task_job.py:221} WARNING - State of this instance has been externally set to success. Terminating instance.
[2022-05-13 06:15:55,918] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 373. PIDs of all processes in the group: [374, 373]
[2022-05-13 06:15:55,921] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 373
[2022-05-13 06:15:55,924] {taskinstance.py:1541} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-05-13 06:15:55,926] {subprocess.py:103} INFO - Sending SIGTERM signal to process group
[2022-05-13 06:15:56,015] {process_utils.py:75} INFO - Process psutil.Process(pid=373, status='terminated', exitcode=0, started='06:14:29') (373) terminated with exit code 0
[2022-05-13 06:15:56,017] {process_utils.py:75} INFO - Process psutil.Process(pid=374, status='terminated', started='06:14:29') (374) terminated with exit code None
