[2022-05-12 07:45:52,012] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: live_stream_Dag.producer_twitter_data manual__2022-05-12T07:45:51.386505+00:00 [queued]>
[2022-05-12 07:45:52,020] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: live_stream_Dag.producer_twitter_data manual__2022-05-12T07:45:51.386505+00:00 [queued]>
[2022-05-12 07:45:52,021] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-05-12 07:45:52,021] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-05-12 07:45:52,022] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-05-12 07:45:52,038] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): producer_twitter_data> on 2022-05-12 07:45:51.386505+00:00
[2022-05-12 07:45:52,042] {standard_task_runner.py:52} INFO - Started process 592 to run task
[2022-05-12 07:45:52,046] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'live_stream_Dag', 'producer_twitter_data', 'manual__2022-05-12T07:45:51.386505+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/live_stream_dag.py', '--cfg-path', '/tmp/tmp6tbvycvi', '--error-file', '/tmp/tmpbgoltqw6']
[2022-05-12 07:45:52,062] {standard_task_runner.py:80} INFO - Job 14: Subtask producer_twitter_data
[2022-05-12 07:45:52,162] {task_command.py:369} INFO - Running <TaskInstance: live_stream_Dag.producer_twitter_data manual__2022-05-12T07:45:51.386505+00:00 [running]> on host 23847fad5ccf
[2022-05-12 07:45:52,478] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Airflow
AIRFLOW_CTX_DAG_ID=live_stream_Dag
AIRFLOW_CTX_TASK_ID=producer_twitter_data
AIRFLOW_CTX_EXECUTION_DATE=2022-05-12T07:45:51.386505+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-05-12T07:45:51.386505+00:00
[2022-05-12 07:45:52,481] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-05-12 07:45:52,483] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python3 /opt/***/dags/producer_tweets.py']
[2022-05-12 07:45:52,494] {subprocess.py:85} INFO - Output:
[2022-05-12 07:45:52,960] {subprocess.py:92} INFO - Traceback (most recent call last):
[2022-05-12 07:45:52,962] {subprocess.py:92} INFO -   File "/opt/***/dags/producer_tweets.py", line 10, in <module>
[2022-05-12 07:45:52,964] {subprocess.py:92} INFO -     consumer_key = config['twitter']['api_key']
[2022-05-12 07:45:52,965] {subprocess.py:92} INFO -   File "/usr/local/lib/python3.7/configparser.py", line 958, in __getitem__
[2022-05-12 07:45:52,967] {subprocess.py:92} INFO -     raise KeyError(key)
[2022-05-12 07:45:52,969] {subprocess.py:92} INFO - KeyError: 'twitter'
[2022-05-12 07:45:52,990] {subprocess.py:96} INFO - Command exited with return code 1
[2022-05-12 07:45:53,013] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-05-12 07:45:53,020] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=live_stream_Dag, task_id=producer_twitter_data, execution_date=20220512T074551, start_date=20220512T074552, end_date=20220512T074553
[2022-05-12 07:45:53,059] {standard_task_runner.py:97} ERROR - Failed to execute job 14 for task producer_twitter_data (Bash command failed. The command returned a non-zero exit code 1.; 592)
[2022-05-12 07:45:53,109] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-05-12 07:45:53,138] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
