[2022-05-12 07:14:32,275] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: live_stream_Dag.producer_twitter_data manual__2022-05-12T07:14:24.929235+00:00 [queued]>
[2022-05-12 07:14:32,281] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: live_stream_Dag.producer_twitter_data manual__2022-05-12T07:14:24.929235+00:00 [queued]>
[2022-05-12 07:14:32,284] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-05-12 07:14:32,285] {taskinstance.py:1357} INFO - Starting attempt 2 of 2
[2022-05-12 07:14:32,286] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-05-12 07:14:32,296] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): producer_twitter_data> on 2022-05-12 07:14:24.929235+00:00
[2022-05-12 07:14:32,300] {standard_task_runner.py:52} INFO - Started process 606 to run task
[2022-05-12 07:14:32,302] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'live_stream_Dag', 'producer_twitter_data', 'manual__2022-05-12T07:14:24.929235+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/live_stream_dag.py', '--cfg-path', '/tmp/tmpafaixbag', '--error-file', '/tmp/tmpjbbe9mq3']
[2022-05-12 07:14:32,304] {standard_task_runner.py:80} INFO - Job 5: Subtask producer_twitter_data
[2022-05-12 07:14:32,349] {task_command.py:369} INFO - Running <TaskInstance: live_stream_Dag.producer_twitter_data manual__2022-05-12T07:14:24.929235+00:00 [running]> on host 176cd38f3c0c
[2022-05-12 07:14:32,472] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Airflow
AIRFLOW_CTX_DAG_ID=live_stream_Dag
AIRFLOW_CTX_TASK_ID=producer_twitter_data
AIRFLOW_CTX_EXECUTION_DATE=2022-05-12T07:14:24.929235+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-05-12T07:14:24.929235+00:00
[2022-05-12 07:14:32,474] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-05-12 07:14:32,475] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python3 /opt/***/dags/producer_tweets.py']
[2022-05-12 07:14:32,482] {subprocess.py:85} INFO - Output:
[2022-05-12 07:14:32,748] {subprocess.py:92} INFO - Traceback (most recent call last):
[2022-05-12 07:14:32,749] {subprocess.py:92} INFO -   File "/opt/***/dags/producer_tweets.py", line 10, in <module>
[2022-05-12 07:14:32,749] {subprocess.py:92} INFO -     consumer_key = config['twitter']['api_key']
[2022-05-12 07:14:32,751] {subprocess.py:92} INFO -   File "/usr/local/lib/python3.7/configparser.py", line 958, in __getitem__
[2022-05-12 07:14:32,752] {subprocess.py:92} INFO -     raise KeyError(key)
[2022-05-12 07:14:32,752] {subprocess.py:92} INFO - KeyError: 'twitter'
[2022-05-12 07:14:32,761] {subprocess.py:96} INFO - Command exited with return code 1
[2022-05-12 07:14:32,772] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-05-12 07:14:32,775] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=live_stream_Dag, task_id=producer_twitter_data, execution_date=20220512T071424, start_date=20220512T071432, end_date=20220512T071432
[2022-05-12 07:14:32,783] {standard_task_runner.py:97} ERROR - Failed to execute job 5 for task producer_twitter_data (Bash command failed. The command returned a non-zero exit code 1.; 606)
[2022-05-12 07:14:32,800] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-05-12 07:14:32,825] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
